"""Generates a downloadable one-page PDF report (reportlab) for an analysis."""
import io

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.platypus import (
    Image as RLImage,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet

from app.image_utils import data_uri_to_bytes


def _styles():
    base = getSampleStyleSheet()
    title = ParagraphStyle(
        "PTTitle", parent=base["Title"], textColor=colors.HexColor("#0891b2")
    )
    heading = ParagraphStyle(
        "PTHeading", parent=base["Heading2"], textColor=colors.HexColor("#1e293b")
    )
    body = ParagraphStyle("PTBody", parent=base["BodyText"], fontSize=10, leading=14)
    small = ParagraphStyle("PTSmall", parent=base["BodyText"], fontSize=8, leading=11,
                            textColor=colors.HexColor("#475569"))
    return title, heading, body, small


def build_report_pdf(analysis: dict) -> bytes:
    """
    Build a one-page PDF summarizing an /api/analyze result:
      - thumbnail of the analyzed image
      - verdict + final score
      - signal breakdown table (name, weight, score, explanation)
      - saliency heatmap image
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        topMargin=0.6 * inch,
        bottomMargin=0.6 * inch,
        leftMargin=0.6 * inch,
        rightMargin=0.6 * inch,
    )
    title_style, heading_style, body_style, small_style = _styles()

    elements = []
    elements.append(Paragraph("PixelTruth &mdash; AI Image Detection Report", title_style))
    elements.append(
        Paragraph(
            "Generated by a custom-trained CNN model (trained from scratch on the "
            "CIFAKE dataset) combined with frequency-domain and metadata analysis. "
            "No third-party AI-detection API was used.",
            small_style,
        )
    )
    elements.append(Spacer(1, 0.2 * inch))

    # --- Thumbnail + verdict side by side ---------------------------------------
    thumb_bytes = data_uri_to_bytes(analysis.get("original_image"))
    verdict = analysis.get("verdict", "Uncertain")
    score = analysis.get("final_score", 0.0)

    verdict_color = colors.HexColor("#16a34a")
    if verdict == "Likely AI-Generated":
        verdict_color = colors.HexColor("#dc2626")
    elif verdict == "Uncertain":
        verdict_color = colors.HexColor("#d97706")

    verdict_style = ParagraphStyle(
        "Verdict", parent=heading_style, textColor=verdict_color, fontSize=16
    )

    left_cell = []
    if thumb_bytes:
        img_buf = io.BytesIO(thumb_bytes)
        left_cell.append(RLImage(img_buf, width=1.8 * inch, height=1.8 * inch))
    else:
        left_cell.append(Paragraph("(no image)", body_style))

    right_cell = [
        Paragraph(f"Verdict: {verdict}", verdict_style),
        Spacer(1, 0.05 * inch),
        Paragraph(f"Combined AI-likelihood score: <b>{score:.1f}%</b>", body_style),
        Paragraph(
            f"Model raw output (P(REAL)): {analysis.get('model_raw_output', 0):.4f}",
            small_style,
        ),
        Paragraph(f"Analysis ID: {analysis.get('analysis_id', '')}", small_style),
    ]

    top_table = Table(
        [[left_cell, right_cell]], colWidths=[2.0 * inch, 4.6 * inch]
    )
    top_table.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    elements.append(top_table)
    elements.append(Spacer(1, 0.25 * inch))

    # --- Signal breakdown table ---------------------------------------------------
    elements.append(Paragraph("Signal Breakdown", heading_style))
    table_data = [["Signal", "Weight", "Score", "Explanation"]]
    for sig in analysis.get("signals", []):
        table_data.append(
            [
                sig.get("name", ""),
                f"{sig.get('weight', 0) * 100:.0f}%",
                f"{sig.get('score', 0):.1f}%",
                Paragraph(sig.get("explanation", ""), small_style),
            ]
        )

    signal_table = Table(table_data, colWidths=[1.5 * inch, 0.7 * inch, 0.7 * inch, 3.7 * inch])
    signal_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f1f5f9")]),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    elements.append(signal_table)
    elements.append(Spacer(1, 0.25 * inch))

    # --- Heatmap ------------------------------------------------------------------
    heatmap_bytes = data_uri_to_bytes(analysis.get("heatmap_image"))
    if heatmap_bytes:
        elements.append(Paragraph("Explainability Heatmap (Input-Gradient Saliency)", heading_style))
        elements.append(
            Paragraph(
                "Brighter regions indicate pixels that most influenced the custom "
                "CNN model's prediction, computed via true gradient backpropagation "
                "through the model's own weights.",
                small_style,
            )
        )
        elements.append(Spacer(1, 0.1 * inch))
        img_buf = io.BytesIO(heatmap_bytes)
        elements.append(RLImage(img_buf, width=2.5 * inch, height=2.5 * inch))

    doc.build(elements)
    return buffer.getvalue()
